// Code generated by "stringer -type=ErrorKind"; DO NOT EDIT.

package requests

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorKindURL-0]
	_ = x[ErrorKindRequest-1]
	_ = x[ErrorKindConnect-2]
	_ = x[ErrorKindValidator-3]
	_ = x[ErrorKindHandler-4]
}

const _ErrorKind_name = "ErrorKindURLErrorKindRequestErrorKindConnectErrorKindValidatorErrorKindHandler"

var _ErrorKind_index = [...]uint8{0, 12, 28, 44, 62, 78}

func (i ErrorKind) String() string {
	if i < 0 || i >= ErrorKind(len(_ErrorKind_index)-1) {
		return "ErrorKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorKind_name[_ErrorKind_index[i]:_ErrorKind_index[i+1]]
}
