// Code generated by "stringer -type=RecorderMode"; DO NOT EDIT.

package reqtest

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModeRecord-0]
	_ = x[ModeReplay-1]
	_ = x[ModeCache-2]
}

const _RecorderMode_name = "ModeRecordModeReplayModeCache"

var _RecorderMode_index = [...]uint8{0, 10, 20, 29}

func (i RecorderMode) String() string {
	if i < 0 || i >= RecorderMode(len(_RecorderMode_index)-1) {
		return "RecorderMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RecorderMode_name[_RecorderMode_index[i]:_RecorderMode_index[i+1]]
}
